export const figmaAssets = {
  logo: "/figma/law-society-logo.png",
  heroCity: "/figma/hero-city.jpg",
  ladyJustice: "/figma/lady-justice.png",
  heroMaroonShape: "/figma/hero-maroon-shape.svg",
  tornTop: "/figma/torn-top.png",
  tornBottom: "/figma/torn-bottom.png",
  tornSection: "/figma/torn-section.png",
  paperTexture: "/figma/paper-texture.png",
  paperTexture2: "/figma/paper-texture-2.png",
  functionClosure: "/figma/function-closure.jpg",
  functionProBono: "/figma/function-pro-bono.jpg",
  functionLibrary: "/figma/function-library.jpg",
  functionDirectory: "/figma/function-directory.jpg",
  anniversary: "/figma/anniversary-group.jpg",
  road: "/figma/road-to-2027.jpg",
  press1: "/figma/press-1.jpg",
  press2: "/figma/press-2.jpg",
  press3: "/figma/press-3.jpg",
  careerBackground: "/figma/career-background.jpg",
  careerPerson: "/figma/career-person.png",
  careerPhone: "/figma/career-phone.png",
  navScales: "/figma/nav-scales.png",
} as const;
